language: java
jdk:
  - openjdk8

install: true

script: - mvn org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

before_install:
  - mvn clean

branches:
 only:
    - master

addons:
  sonarcloud:
    organization: "deeplyocean-github"
    token:
      secure: "f1e81591eca2610504765c2cd05ada5a74ac98a2"

#after_success:
#  -

#notifications:
#  slack:
