language: java

jdk:
  - openjdk8

install: true

addons:
  sonarcloud:
    organization: "deeplyocean-github"
    token:
      secure: "f1e81591eca2610504765c2cd05ada5a74ac98a2"
      
script: 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

before_install:
  - mvn clean

branches:
 only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
#after_success:
#  -

#notifications:
#  slack:
