language: java
jdk:
  - openjdk8

install: true

script: mvn cobertura:cobertura

before_install:
  - mvn clean

branches:
 only:
    - master

after_success:
  - bash <(curl -s https://codecov.io/bash)

#notifications:
#  slack:
