version: 2
jobs:
  build:    
    working_directory: ~/ocean

    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run: mvn clean package dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: ocean-{{ checksum "pom.xml" }}
      
#      - store_artifacts:
#          path: target/ocean.war
